### PR TITLE
Switch to pipenv

### PR DESCRIPTION
**Pull request by jcarbaugh**
It's pipenv time!

### CODE REVIEW

**Comment by CorneliusIV** [comment]
@jcarbaugh Want to update the readme, and double check the versions? After that, I say we merge this.

**Comment by jcarbaugh** [comment]
@CorneliusIV rebased from master and updated READMEs. I'm good to go with this now.

**Comment by oudeismetis** [comment]
seems good

**Comment by jcarbaugh** [comment]
@laughtonm I'm going to vote no on the lock file for the generated project. I'd rather those be updated upon project creation, then the lock file can be checked in with that initial commit.

**Comment by laughtonm** [comment]
@jcarbaugh - I totally agree :) I probably should have been explicit - here, I was really just referring to the associated lock with the root project

**Comment by jcarbaugh** [comment]
@laughtonm I'm neutral on the lock file here. It's only going to be used if someone is working on mo-django itself or when tests run on Circle. What do you think?

**Pull request merged**
