### PR TITLE
Upgrade Django to 1.10

### PR DESCRIPTION
**Pull request by CorneliusIV**
Upgrade Django to 1.10 and Django Debug Toolbar to 1.5 which is compatible with Django 1.10

### CODE REVIEW

**Comment by g3rd** [comment]
White noise might need upgraded too. Django 1.10 changed how middleware is handled.

**Comment by CorneliusIV** [comment]
@g3rd thanks will take a look

**Comment by joesolly** [comment]
@CorneliusIV also, take a look at this. they removed MIDDLEWARE_CLASSES https://docs.djangoproject.com/en/1.10/topics/http/middleware/#activating-middleware

**Comment by akrawchyk** [comment]
@joesolly see https://github.com/istrategylabs/mo-django/issues/51

**Comment by akrawchyk** [comment]
@CorneliusIV need to update the `MIDDLEWARE_CLASSES` setting here https://github.com/istrategylabs/mo-django/blob/cafe8ed43cbf2e88f5a82c3dd82dbb5ea68d445f/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/settings.py#L49 per https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware

**Comment by joesolly** [comment]
@CorneliusIV sslify is now compatible with Django 1.10 if we would like to continue using it.

**Comment by jcarbaugh** [comment]
Probably don't need sslify any longer, unless there is a compelling reason that people have uncovered. Seeing as how that's the only non-Django middleware, upgrading to new-style middleware should be good here.

**Comment by CorneliusIV** [comment]
@joesolly @akrawchyk updated the middleware I am assuming  'sslify.middleware.SSLifyMiddleware', will be removed in https://github.com/istrategylabs/mo-django/pull/53

**Comment by akrawchyk** [comment]
Please update all references in the comments in `settings.py` to Django 1.10, for example https://github.com/istrategylabs/mo-django/blob/87b830a1234e97657c78a84b63e1579bfc79656a/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/settings.py#L5

**Comment by CorneliusIV** [comment]
We are still waiting on the Debug Tool Bar to be upgraded before we can really pull this

**Comment by akrawchyk** [comment]
I'm also running into this issue with django 1.10 and django-rq https://github.com/ui/django-rq/issues/180

**Comment by akrawchyk** [comment]
Need to upgrade `django-rq` to at least `0.9.3`, see https://github.com/ui/django-rq/issues/195#issuecomment-255274403

**Comment by joesolly** [comment]
👍

**Comment by jcarbaugh** [comment]
👍 code

**Pull request merged**
